version: '3'
services:
  web:
    build: .
    ports:
      - '8080:80'
  db: 
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/sql/
