version: '3'
services:
  web:
    build: .
    ports: 
      - '8080:8080'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db/mydb
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/sql/
